spring:
  application:
    name: netflix-zuul-api-gateway
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8041
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    review-service:
      path: /product-review/**
    product-service:
      path: /productzuul/**
  ignored-services:
    - review-service


